#!/bin/sh
module="buttons"
device="buttons"
mode="664"

rmmod $module
insmod ./$module.ko $* || exit 1

rm -f /dev/${device}

major=$(awk '$2=="'$module'" {print $1}' /proc/devices)
echo $major

mknod /dev/${device} c ${major} 0
